name: plas_track2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  cloud_firestore: ^4.17.2
  firebase_auth: ^4.19.4
  firebase_core: ^2.30.1
  flutter:
    sdk: flutter
  flutter_map: ^6.1.0
  google_sign_in: ^6.2.1
  intl: ^0.19.0
  latlong2: ^0.9.1
  razorpay_flutter: ^1.3.3
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "images/logoc.png"

flutter:
  uses-material-design: true
  assets:
    - images/
